---
sidebar: sidebar 
permalink: use/capacity-add.html 
keywords: economic efficiency remediate, economic efficiency, capacity planning, add capacity 
summary: 경제적인 효율성 서비스는 예상되는 데이터 증가에 따라 AFF 시스템에 대한 권장 사항을 제공합니다. 예측을 수락하거나 자체 예측을 입력할 수 있습니다. 이 서비스를 통해 용량 증가 예측을 충족하고 자산 구성에 가장 적합한 권장 사항을 제시합니다. 
---
= 용량 추가
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
경제적인 효율성 서비스는 예상되는 데이터 증가에 따라 AFF 시스템에 대한 권장 사항을 제공합니다. 예측을 수락하거나 자체 예측을 입력할 수 있습니다. 이 서비스를 통해 용량 증가 예측을 충족하고 자산 구성에 가장 적합한 권장 사항을 제시합니다.

권장 사항 중 하나는 기존 일련 번호에 쉘프를 추가하여 용량을 추가하는 것입니다.

NetApp 세일즈 팀에 견적 요청 또는 대체 옵션 요청을 위해 권장사항을 쉽게 제출할 수 있습니다.

.단계
. BlueXP 왼쪽 탐색 창에서 * Governance * > * Economic Efficiency * > * Capacity Planning * 을 선택합니다.
. 자산에 대해 * 스토리지 옵션 평가 * 를 선택합니다.
. 용량 추가 * 를 선택합니다.
+
자산의 데이터가 나타납니다.

+
** 예측, 활용률, 지연 시간 동향 및 IOPS 추세를 검토합니다.
** 권장 사항을 얻으려면 * 스토리지 옵션 평가 * 를 선택합니다.
+
용량 요구사항 정의 페이지에는 현재 및 예상 용량 예측과 예상 증가에 따른 권장 애드온 스토리지가 표시됩니다.



. 오른쪽에 있는 옵션 중 하나를 선택합니다.
+
** * 예측된 성장 * 을 기반으로 애드온 스토리지를 권장하고 선택적으로 버퍼 비율을 추가합니다.
** * 맞춤형 데이터 증가 * 를 기준으로 애드온 스토리지를 권장하며 권장되는 용량이 아닌 원하는 총 애드온 용량을 입력합니다.


. Continue * 를 선택합니다.
+
권장 사항 세트가 나타납니다.

. 선택한 자산 일련 번호에 대한 권장 사항을 검토하십시오.
. 다음 중 하나를 수행합니다.
+
** 권장 사항을 수락하려면 * 다음 * 을 선택합니다. 이 요청은 필요한 추가 용량을 얻기 위해 귀사와 협력할 수 있는 NetApp 세일즈 전문가에게 전송됩니다.
** 다른 옵션을 요청하려면 * 대체 옵션 요청 * 을 선택하고 요청을 입력한 다음 * 이메일 전송 * 을 선택합니다. 용량 요구 사항을 해결하기 위해 연락을 드릴 NetApp 세일즈 전문가에게 이메일이 전송됩니다.


. 추가 용량에 대한 요청을 검토하고 * 확인 및 제출 * 을 선택합니다.
+
용량 계획 상태 페이지가 나타납니다.

. 용량 계획 상태 페이지에서 상태를 검토합니다.

