---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: economic efficiency faq, bluexp, economic efficiency frequently asked questions 
summary: 'BlueXP 경제적 효율성 서비스는 현재 또는 예상 용량이 낮은 클러스터를 식별하고 데이터 계층화 또는 추가 용량(AFF 시스템의 경우)에 대한 권장 사항을 제공합니다. 또한 수명이 거의 다 된 시스템에 대한 기술 업데이트 권장 사항을 제공합니다.' 
---
= 새로운 기능
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BlueXP의 새로운 경제 효율성에 대해 알아보십시오.



== 2024년 5월 15일

일부 BlueXP 의 경제적 효율성 기능이 일시적으로 비활성화되었습니다.

* 기술 교체
* 용량 추가




== 2024년 3월 14일

기존 자산이 있고 기술을 업데이트해야 하는지 여부를 확인하려면 BlueXP의 경제적 효율성 기술 업데이트 옵션을 사용할 수 있습니다. 현재 워크로드에 대한 간단한 평가를 검토하여 추천을 하거나 지난 90일 이내에 AutoSupport 로그를 NetApp에 보낸 경우, 이제 워크로드 시뮬레이션을 제공하여 새로운 하드웨어에서 워크로드가 어떻게 수행되는지 확인할 수 있습니다.

또한 워크로드를 추가하고 기존 워크로드를 시뮬레이션에서 제외할 수 있습니다.

이전에는 자산을 평가하고 기술 업데이트가 필요한지 여부만 파악할 수 있었습니다.

이 기능은 이제 왼쪽 탐색 창의 Tech Refresh 옵션에 포함됩니다.

에 대해 자세히 알아보십시오 link:../use/tech-refresh.html["기술 업데이트를 평가합니다"].



== 2023년 11월 8일

이번 BlueXP의 경제적 효율성 릴리즈에는 자산을 평가하고 기술 업데이트가 권장되는지 여부를 확인할 수 있는 새로운 옵션이 포함되어 있습니다. 이 서비스에는 왼쪽 탐색 창에 있는 새로운 기술 업데이트 옵션, 현재 워크로드와 자산을 평가할 수 있는 새 페이지, 권장사항이 있는 보고서가 포함되어 있습니다.



== 2023년 4월 2일

새로운 BlueXP 경제적 효율성 서비스는 현재 또는 예상되는 낮은 용량의 스토리지 자산을 식별하고 사내 AFF 시스템의 데이터 계층화 또는 추가 용량에 대한 권장 사항을 제공합니다.

link:https://docs.netapp.com/us-en/bluexp-economic-efficiency/get-started/intro.html["BlueXP의 경제적 효율성에 대해 자세히 알아보십시오"].
